---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fastapi-services
  description: Sistema que agrupa APIs baseadas em FastAPI
spec:
  owner: group:devs

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-fastapi
  description: Exemplo de API gerada via template
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:devs
  system: fastapi-services
