
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-tools
  description: Serviços voltados ao desenvolvimento
spec:
  owner: group:platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fastapi-service
  description: API de backend desenvolvida em FastAPI
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:platform-team
  system: developer-tools
  providesApis:
    - fastapi-service-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-frontend
  description: Aplicação frontend em React
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: group:frontend-team
  system: developer-tools
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fastapi-service-api
  description: API exposta pela aplicação FastAPI
spec:
  type: openapi
  lifecycle: production
  owner: group:platform-team
  system: developer-tools
  definition:
    $text: https://raw.githubusercontent.com/<ORG>/<REPO>/main/openapi.yaml
